/** Ciudades principales de Ecuador ordenadas alfabéticamente */
export const CIUDADES_ECUADOR = [
  "Ambato",
  "Atacames",
  "Azogues",
  "Babahoyo",
  "Bahía de Caráquez",
  "Balzar",
  "Baños de Agua Santa",
  "Calceta",
  "Cayambe",
  "Chone",
  "Coca (Puerto Francisco de Orellana)",
  "Cuenca",
  "Daule",
  "Durán",
  "El Carmen",
  "Esmeraldas",
  "Guaranda",
  "Guayaquil",
  "Huaquillas",
  "Ibarra",
  "Jipijapa",
  "La Libertad",
  "La Maná",
  "Lago Agrio (Nueva Loja)",
  "Latacunga",
  "Loja",
  "Machachi",
  "Machala",
  "Manta",
  "Milagro",
  "Montecristi",
  "Muisne",
  "Naranjal",
  "Naranjito",
  "Otavalo",
  "Pasaje",
  "Pedernales",
  "Playas (General Villamil)",
  "Portoviejo",
  "Puyo",
  "Quevedo",
  "Quito",
  "Riobamba",
  "Rosa Zárate (Quinindé)",
  "Salinas",
  "Sangolquí",
  "Santa Elena",
  "Santa Rosa",
  "Santo Domingo",
  "Shushufindi",
  "Tena",
  "Tulcán",
  "Ventanas",
  "Vinces",
  "Zamora",
] as const;

export type CiudadEcuador = (typeof CIUDADES_ECUADOR)[number];
